name: Deploy PWA Booksmart

on:
  push:
    branches: [ "main" ]

# Permisos necesarios para organizaciones y despliegue de Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # --- ETAPA DE SEGURIDAD: Trivy ---
      - name: Escaneo de vulnerabilidades con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Detiene el flujo si hay vulnerabilidades graves

      # --- ETAPA DE CONSTRUCCIÓN: Bun ---
      - name: Configurar Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Instalar dependencias
        run: bun install

      - name: Build de Angular PWA
        # Se usa el base-href para que los assets carguen bien en mavedevs.github.io/booksmart_pwa/
        run: bun run build -- --configuration production --base-href /booksmart_pwa/

      # --- ETAPA DE DESPLIEGUE: GitHub Pages ---
      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/booksmart_pwa/browser
          branch: gh-pages
          clean: true # Elimina archivos viejos en la rama gh-pages